#%RAML 1.0
title: FPL Payment Exp API
/fplPaymentDetails:
    post:
      description: FPL PAYMENT EXP API
      body:
        application/json:
          example:
            {
   	"customer number":"123654"
            } 

      responses:
        200:
          body:
            application/json:
              example:
                {
                  
  "NAME": "XYZ",  
  "Company": "ABCD",
	"customer number":"123654"
  }
      

